### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Octaviocossy** [weizheheng/nvim-workbench#2]
Hi, I followed the installation steps as is and it throws these errors at me, when opening neovim and when I run some referic command to the plugin. attached captures.
![1](https://user-images.githubusercontent.com/72137526/116080223-2b1f8a00-a66f-11eb-9d19-36b15312e6c2.png)
![2](https://user-images.githubusercontent.com/72137526/116080231-2ce94d80-a66f-11eb-9830-7da3e83e068a.png)
I'm very interested in this plugin haha!

**Comment by weizheheng** [comment]
@Octaviocossy, thank you for the interest, hmm, It is working fine on my end. Can you try running this in your neovim?

```vim
:lua require('workbench').toggle()
```

**Comment by weizheheng** [comment]
@Octaviocossy Hi, I get to reproduce the error if I am on Nvim v0.4.4. Are you on this version? Sorry for that, I will need to update the README saying that it requires Nvim nightly for this plugin to work until I get it working on v0.4.4 as well. Maybe you can try installing Nvim nightly if you really want to test this out :) I am loving it myself so far.

**Comment by Octaviocossy** [comment]
Yes, I'm using version 0.4.4, thanks for the help, I'll wait for the version of 0.4.4 :)

**Comment by weizheheng** [comment]
@Octaviocossy Hi, I took some time to add support for 0.4.4. You should be able to launch it now. However, nvim 0.4.4 does not have built-in support to create a border for floating windows, so the workbench you will see right now is borderless unfortunately :(

**Comment by Octaviocossy** [comment]
Thank you very much for taking the time to add support for 0.4.4, I am using the plugin perfectly, thanks. :)
