### ISSUE TITLE
Workbench not showing Neovim 0.5

### ISSUE THREAD

**Issue by Vanderscycle** [weizheheng/nvim-workbench#4]
Hey,

I installed nvim-workbench through Packer, but nothing is happening and I am not getting any errors. I confirmed that the files were downloaded locally and tried :ToggleProjectWorkbench / :help workbench (see if there was documentation) but nothing came up. I did see ~/.cache/workbench created.

Its possible that the issue is on my end but I am unsure if the plugin can conflict with themes or other plugins.

I like the plugins idea tho.

**Comment by weizheheng** [comment]
Hi, thank you so much for your interest in this plugin. If the workbench directory is created, it should be installed properly. Did you set the key mapping already? And are there any errors popping up when you trying to toggle the workbench?

- You can try this and see if it works, let me know if you see any errors when running the below command.
```vim
" This will toggle a project specific workbench
:lua require('workbench').toggle_project_workbench()

" This will toggle a git branch specific workbench
:lua require('workbench').toggle_branch_workbench()
```

**Comment by Vanderscycle** [comment]
Interresting, I do get a response now, but its telling me that its not a git repo even tho theres a repo in there. I am using Vim fugitive.
Before:
![issuebefore](https://user-images.githubusercontent.com/52706578/117092257-9eca3280-ad12-11eb-81d8-20db376123aa.png)
after:
![issueafter](https://user-images.githubusercontent.com/52706578/117092268-a558aa00-ad12-11eb-88c5-aa7232201583.png)

**Comment by weizheheng** [comment]
Shouldn't be a problem, I am using vim-fugitive myself as well. It seems like you are not currently on the correct path.

Can you share with me what is the output of `:pwd` ?

**Comment by Vanderscycle** [comment]
I am in the correct directory. I went through the plugin code and you don't call the terminal when using the plugin do you?

**Comment by weizheheng** [comment]
Yeap you are right. I am not using the terminal at all. I am only creating a buffer and then opening a floating window using `nvim_open_win`. The error message above will only be returned if `is_git_repo` function returns a value other than true.

You can try running this in your current directory, I am using the git built-in function to check whether the current directory is a git directory
```
:echo system("git rev-parse --is-inside-work-tree")
```

**Comment by Vanderscycle** [comment]
Returns true, is it possible tat it spawns the buffer inside nvim-tree?

**Comment by weizheheng** [comment]
Hmm, I can't seem to reproduce your error. If you don't mind, can you share the output for this command here?
```vim
:lua print(require('workbench.utils').is_git_repo())
```

- Also, have you tried toggling the workbench in a different project?
- Does the branch-specific workbench returns the same error?
```vim
:lua require('workbench').toggle_branch_workbench()
```

**Comment by Vanderscycle** [comment]
Thanks for the help, I'll keep troubleshooting on my end and reopen the issue if I find what caused it.

**Comment by weizheheng** [comment]
No worry @Vanderscycle  feel free to just ping me here if you need any helps to troubleshoot. Hope you can get it to work soon :)

I think we are almost there, can you share with me the output of this?

```vim
:lua print(vim.inspect(require('workbench.utils').is_git_repo()))
```

**Comment by Vanderscycle** [comment]
Hey, so I tried the commands again, and its working (idk what I was doing wrong yesterday) and its consistent. I changed my nvim keybindings to essentially be:
~~~lua
-- I know its not proper lua
<leader>bp,:lua require('workbench').toggle_project_workbench()
<leader>bb,:lua require('workbench').toggle_branch_workbench()
-- for the checkboxes
vim.cmd([[nmap <leader>ba <Plug>WorkbenchAddCheckbox]])
vim.cmd([[nmap <leader>bc <Plug>WorkbenchToggleCheckbox]])
~~~
I am having minor graphical issue when adding a box (something to do with visual block)
before adding a box
![issuebefore](https://user-images.githubusercontent.com/52706578/117196893-f5c81a00-ad9b-11eb-9d38-d47add01242b.png)
after adding a box
![issueafter](https://user-images.githubusercontent.com/52706578/117196902-f791dd80-ad9b-11eb-819e-aa3473aa5e8b.png)

**Comment by weizheheng** [comment]
Hi, glad that you got it working. Hmm yeah, this is the problem that's bugging me a lot while I am building this plugin. Basically `WorkbenchAddCheckbox` is doing a vim `search and replace` under the hood.  And it seems like there is no way to prevent vim from highlighting other matches (there are many suggestions out there but not really solving the underlying issue), I should add this to the README maybe under `Caveat` section. Do you know any solution to this?

This doesn't happen to me because I set my neovim to not have highlight for searches, and I have a key bind to toggle the highlight when I needed them.

```vim
" no highlight for searches
set nohls
" Toggle highlight
noremap  <leader>h :set invhlsearch hlsearch?<CR>
```

**Comment by Vanderscycle** [comment]
I unfortunately don't know the solution. I only started using vim/nvim two months ago and the learning curve has been steep. I need to make a push learning lua and reading nvim config files more.

Not sure if disabling the option (highlight), checking or create the check box and then reenabling the option would prove feasible.

I will close my issue, and learn about how highlighting is done.

**Comment by rohit-kumar-j** [comment]
For future readers, example in pure lua api:

```lua
vim.api.nvim_set_keymap('n',"<leader><leader>p" ,"<cmd>lua require('workbench').toggle_project_workbench()<CR>",  {noremap = true, silent = true, desc = "Toggle Project Workbench"})
vim.api.nvim_set_keymap('n',"<leader><leader>b" ,"<cmd>lua require('workbench').toggle_branch_workbench()<CR>",  {noremap = true, silent = true , desc = "Toggle Branch Workbench"})
vim.api.nvim_set_keymap('n',"<leader><leader>a" ,"<Plug>WorkbenchAddCheckbox<CR>",  {noremap = true, silent = true , desc = "Add CheckBox"})
vim.api.nvim_set_keymap('n',"<leader><leader>t" ,"<Plug>WorkbenchToggleCheckbox<CR>",  {noremap = true, silent = true , desc = "Toggle CheckBox"})
```
