### ISSUE TITLE
Autosaving files on buffer change

### ISSUE THREAD

**Issue by pipoprods** [weizheheng/nvim-workbench#8]
This plugin is exactly what I was planning to develop myself, thanks for it!

I've got an issue with this line:

https://github.com/marcushwz/nvim-workbench/blob/main/plugin/nvim-workbench.vim#L35

I'm using `vim.opt.hidden = true` so changing buffer is not supposed to trigger a file save.

I could submit a patch but I don't really get the use of this line…

**Comment by weizheheng** [comment]
Hey there, glad that you find this plugin useful :) Haven't been working on it for quite some time and I actually changed it to only save files related to this plugin on my local. This is now pushed to main. Not sure if this helps for your use case?

```vim
" Autosave on buf leave
au BufLeave workbench.md silent! wall
au BufLeave *branchbench.md silent! wall
```

**Comment by pipoprods** [comment]
Yes, it fixes it, thanks a lot!
