### ISSUE TITLE
Cannot create directory ~/.cache/workbench: file already exists

### ISSUE THREAD

**Issue by alok** [weizheheng/nvim-workbench#9]
I get this error on the latest update. I can't post an issue in the newer version, so here we are. Maybe a mkdir should be `mkdir -p`?

**Comment by weizheheng** [comment]
Hi, thanks for the issue, this should be fixed now in the latest main branch, can you try updating and see if it works?

The command to create directory is updated to:
```vim
vim.fn.mkdir("/Users/username/.cache/workbench", "p")
```
